In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
df = pd.read_parquet("eda_banking.parquet")
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned,Fraud,RiskScore,BalancePerProduct,AgeRisk,HighValueCustomer,LowCreditRisk,MarketingScore,ComplainFlag,LowSatisfaction,OperationalRiskScore,event_timestamp,customer_id
0,619,France,Female,42,2,11983969.0,1,1,1,10134888.0,1,1,2,DIAMOND,464,0,1,0.000000,0,0,0,0,1,1,2,2024-01-01 00:00:00,ADX_0
1,608,Spain,Female,41,1,8380786.0,1,0,1,11254258.0,0,1,3,DIAMOND,456,0,1,41903.930000,0,0,0,1,1,0,1,2024-01-01 00:01:00,ADX_1
2,502,France,Female,42,8,15966080.0,3,1,0,11393157.0,1,1,3,DIAMOND,377,0,3,39915.200000,0,1,0,1,1,0,2,2024-01-01 00:02:00,ADX_2
3,699,France,Female,39,1,11983969.0,2,0,0,9382663.0,0,0,5,GOLD,350,0,1,0.000000,0,0,0,0,0,0,1,2024-01-01 00:03:00,ADX_3
4,850,Spain,Female,43,2,12551082.0,1,1,1,7908410.0,0,0,5,GOLD,425,0,1,62755.410000,0,1,0,2,0,0,0,2024-01-01 00:04:00,ADX_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,11983969.0,2,1,0,9627064.0,0,0,1,DIAMOND,300,0,1,0.000000,0,0,0,0,0,1,2,2024-01-07 22:35:00,ADX_9995
9996,516,France,Male,35,10,5736961.0,1,1,1,10169977.0,0,0,5,PLATINUM,771,0,0,28684.805000,0,0,0,0,0,0,0,2024-01-07 22:36:00,ADX_9996
9997,709,France,Female,36,7,11983969.0,1,0,1,4208558.0,1,1,3,SILVER,564,0,1,0.000000,0,0,0,0,1,0,1,2024-01-07 22:37:00,ADX_9997
9998,772,Germany,Male,42,3,7507531.0,2,1,0,9288852.0,1,1,2,GOLD,339,1,2,25025.103333,0,0,0,1,1,1,3,2024-01-07 22:38:00,ADX_9998
9999,792,France,Female,28,4,13014279.0,1,1,0,3819078.0,0,0,3,DIAMOND,911,0,2,65071.395000,0,1,0,1,0,0,1,2024-01-07 22:39:00,ADX_9999

In [2]:
df["event_timestamp"] = pd.date_range(start="2024-01-01", periods=len(df), freq="T")

# Create a unique customer_id for each row
df["customer_id"] = [f"ADX_{i}" for i in range(len(df))]
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned,Fraud,RiskScore,BalancePerProduct,AgeRisk,HighValueCustomer,LowCreditRisk,MarketingScore,ComplainFlag,LowSatisfaction,OperationalRiskScore,event_timestamp,customer_id
0,619,France,Female,42,2,11983969.0,1,1,1,10134888.0,1,1,2,DIAMOND,464,0,1,0.000000,0,0,0,0,1,1,2,2024-01-01 00:00:00,ADX_0
1,608,Spain,Female,41,1,8380786.0,1,0,1,11254258.0,0,1,3,DIAMOND,456,0,1,41903.930000,0,0,0,1,1,0,1,2024-01-01 00:01:00,ADX_1
2,502,France,Female,42,8,15966080.0,3,1,0,11393157.0,1,1,3,DIAMOND,377,0,3,39915.200000,0,1,0,1,1,0,2,2024-01-01 00:02:00,ADX_2
3,699,France,Female,39,1,11983969.0,2,0,0,9382663.0,0,0,5,GOLD,350,0,1,0.000000,0,0,0,0,0,0,1,2024-01-01 00:03:00,ADX_3
4,850,Spain,Female,43,2,12551082.0,1,1,1,7908410.0,0,0,5,GOLD,425,0,1,62755.410000,0,1,0,2,0,0,0,2024-01-01 00:04:00,ADX_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,11983969.0,2,1,0,9627064.0,0,0,1,DIAMOND,300,0,1,0.000000,0,0,0,0,0,1,2,2024-01-07 22:35:00,ADX_9995
9996,516,France,Male,35,10,5736961.0,1,1,1,10169977.0,0,0,5,PLATINUM,771,0,0,28684.805000,0,0,0,0,0,0,0,2024-01-07 22:36:00,ADX_9996
9997,709,France,Female,36,7,11983969.0,1,0,1,4208558.0,1,1,3,SILVER,564,0,1,0.000000,0,0,0,0,1,0,1,2024-01-07 22:37:00,ADX_9997
9998,772,Germany,Male,42,3,7507531.0,2,1,0,9288852.0,1,1,2,GOLD,339,1,2,25025.103333,0,0,0,1,1,1,3,2024-01-07 22:38:00,ADX_9998
9999,792,France,Female,28,4,13014279.0,1,1,0,3819078.0,0,0,3,DIAMOND,911,0,2,65071.395000,0,1,0,1,0,0,1,2024-01-07 22:39:00,ADX_9999

In [3]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [4]:
df['event_timestamp'].to_dict()

{0: Timestamp('2024-01-01 00:00:00'),
 1: Timestamp('2024-01-01 00:01:00'),
 2: Timestamp('2024-01-01 00:02:00'),
 3: Timestamp('2024-01-01 00:03:00'),
 4: Timestamp('2024-01-01 00:04:00'),
 5: Timestamp('2024-01-01 00:05:00'),
 6: Timestamp('2024-01-01 00:06:00'),
 7: Timestamp('2024-01-01 00:07:00'),
 8: Timestamp('2024-01-01 00:08:00'),
 9: Timestamp('2024-01-01 00:09:00'),
 10: Timestamp('2024-01-01 00:10:00'),
 11: Timestamp('2024-01-01 00:11:00'),
 12: Timestamp('2024-01-01 00:12:00'),
 13: Timestamp('2024-01-01 00:13:00'),
 14: Timestamp('2024-01-01 00:14:00'),
 15: Timestamp('2024-01-01 00:15:00'),
 16: Timestamp('2024-01-01 00:16:00'),
 17: Timestamp('2024-01-01 00:17:00'),
 18: Timestamp('2024-01-01 00:18:00'),
 19: Timestamp('2024-01-01 00:19:00'),
 20: Timestamp('2024-01-01 00:20:00'),
 21: Timestamp('2024-01-01 00:21:00'),
 22: Timestamp('2024-01-01 00:22:00'),
 23: Timestamp('2024-01-01 00:23:00'),
 24: Timestamp('2024-01-01 00:24:00'),
 25: Timestamp('2024-01-01 00:25:00'),
 26: Timestamp('2024-01-01 00:26:00'),
 27: Timestamp('2024-01-01 00:27:00'),
 28: Timestamp('2024-01-01 00:28:00'),
 29: Timestamp('2024-01-01 00:29:00'),
 30: Timestamp('2024-01-01 00:30:00'),
 31: Timestamp('2024-01-01 00:31:00'),
 32: Timestamp('2024-01-01 00:32:00'),
 33: Timestamp('2024-01-01 00:33:00'),
 34: Timestamp('2024-01-01 00:34:00'),
 35: Timestamp('2024-01-01 00:35:00'),
 36: Timestamp('2024-01-01 00:36:00'),
 37: Timestamp('2024-01-01 00:37:00'),
 38: Timestamp('2024-01-01 00:38:00'),
 39: Timestamp('2024-01-01 00:39:00'),
 40: Timestamp('2024-01-01 00:40:00'),
 41: Timestamp('2024-01-01 00:41:00'),
 42: Timestamp('2024-01-01 00:42:00'),
 43: Timestamp('2024-01-01 00:43:00'),
 44: Timestamp('2024-01-01 00:44:00'),
 45: Timestamp('2024-01-01 00:45:00'),
 46: Timestamp('2024-01-01 00:46:00'),
 47: Timestamp('2024-01-01 00:47:00'),
 48: Timestamp('2024-01-01 00:48:00'),
 49: Timestamp('2024-01-01 00:49:00'),
 50: Timestamp('2024-01-01 00:50:00'),
 51: Timestamp('2024-01-01 00:51:00'),
 52: Timestamp('2024-01-01 00:52:00'),
 53: Timestamp('2024-01-01 00:53:00'),
 54: Timestamp('2024-01-01 00:54:00'),
 55: Timestamp('2024-01-01 00:55:00'),
 56: Timestamp('2024-01-01 00:56:00'),
 57: Timestamp('2024-01-01 00:57:00'),
 58: Timestamp('2024-01-01 00:58:00'),
 59: Timestamp('2024-01-01 00:59:00'),
 60: Timestamp('2024-01-01 01:00:00'),
 61: Timestamp('2024-01-01 01:01:00'),
 62: Timestamp('2024-01-01 01:02:00'),
 63: Timestamp('2024-01-01 01:03:00'),
 64: Timestamp('2024-01-01 01:04:00'),
 65: Timestamp('2024-01-01 01:05:00'),
 66: Timestamp('2024-01-01 01:06:00'),
 67: Timestamp('2024-01-01 01:07:00'),
 68: Timestamp('2024-01-01 01:08:00'),
 69: Timestamp('2024-01-01 01:09:00'),
 70: Timestamp('2024-01-01 01:10:00'),
 71: Timestamp('2024-01-01 01:11:00'),
 72: Timestamp('2024-01-01 01:12:00'),
 73: Timestamp('2024-01-01 01:13:00'),
 74: Timestamp('2024-01-01 01:14:00'),
 75: Timestamp('2024-01-01 01:15:00'),
 76: Timestamp('2024-01-01 01:16:00'),
 77: Timestamp('2024-01-01 01:17:00'),
 78: Timestamp('2024-01-01 01:18:00'),
 79: Timestamp('2024-01-01 01:19:00'),
 80: Timestamp('2024-01-01 01:20:00'),
 81: Timestamp('2024-01-01 01:21:00'),
 82: Timestamp('2024-01-01 01:22:00'),
 83: Timestamp('2024-01-01 01:23:00'),
 84: Timestamp('2024-01-01 01:24:00'),
 85: Timestamp('2024-01-01 01:25:00'),
 86: Timestamp('2024-01-01 01:26:00'),
 87: Timestamp('2024-01-01 01:27:00'),
 88: Timestamp('2024-01-01 01:28:00'),
 89: Timestamp('2024-01-01 01:29:00'),
 90: Timestamp('2024-01-01 01:30:00'),
 91: Timestamp('2024-01-01 01:31:00'),
 92: Timestamp('2024-01-01 01:32:00'),
 93: Timestamp('2024-01-01 01:33:00'),
 94: Timestamp('2024-01-01 01:34:00'),
 95: Timestamp('2024-01-01 01:35:00'),
 96: Timestamp('2024-01-01 01:36:00'),
 97: Timestamp('2024-01-01 01:37:00'),
 98: Timestamp('2024-01-01 01:38:00'),
 99: Timestamp('2024-01-01 01:39:00'),
 100: Timestamp('2024-01-01 01:40:00'),
 101: Timestamp('2024-01-01 01:41:00'),
 102: Timestamp('2024-01-01 01:42:00'),
 103: Timestamp('2024-01-01 01:43:00'),
 104: Timestamp('2024-01-01 01:44:00'),
 105: Timestamp('2024-01-01 01:45:00'),
 106: Timestamp('2024-01-01 01:46:00'),
 107: Timestamp('2024-01-01 01:47:00'),
 108: Timestamp('2024-01-01 01:48:00'),
 109: Timestamp('2024-01-01 01:49:00'),
 110: Timestamp('2024-01-01 01:50:00'),
 111: Timestamp('2024-01-01 01:51:00'),
 112: Timestamp('2024-01-01 01:52:00'),
 113: Timestamp('2024-01-01 01:53:00'),
 114: Timestamp('2024-01-01 01:54:00'),
 115: Timestamp('2024-01-01 01:55:00'),
 116: Timestamp('2024-01-01 01:56:00'),
 117: Timestamp('2024-01-01 01:57:00'),
 118: Timestamp('2024-01-01 01:58:00'),
 119: Timestamp('2024-01-01 01:59:00'),
 120: Timestamp('2024-01-01 02:00:00'),
 121: Timestamp('2024-01-01 02:01:00'),
 122: Timestamp('2024-01-01 02:02:00'),
 123: Timestamp('2024-01-01 02:03:00'),
 124: Timestamp('2024-01-01 02:04:00'),
 125: Timestamp('2024-01-01 02:05:00'),
 126: Timestamp('2024-01-01 02:06:00'),
 127: Timestamp('2024-01-01 02:07:00'),
 128: Timestamp('2024-01-01 02:08:00'),
 129: Timestamp('2024-01-01 02:09:00'),
 130: Timestamp('2024-01-01 02:10:00'),
 131: Timestamp('2024-01-01 02:11:00'),
 132: Timestamp('2024-01-01 02:12:00'),
 133: Timestamp('2024-01-01 02:13:00'),
 134: Timestamp('2024-01-01 02:14:00'),
 135: Timestamp('2024-01-01 02:15:00'),
 136: Timestamp('2024-01-01 02:16:00'),
 137: Timestamp('2024-01-01 02:17:00'),
 138: Timestamp('2024-01-01 02:18:00'),
 139: Timestamp('2024-01-01 02:19:00'),
 140: Timestamp('2024-01-01 02:20:00'),
 141: Timestamp('2024-01-01 02:21:00'),
 142: Timestamp('2024-01-01 02:22:00'),
 143: Timestamp('2024-01-01 02:23:00'),
 144: Timestamp('2024-01-01 02:24:00'),
 145: Timestamp('2024-01-01 02:25:00'),
 146: Timestamp('2024-01-01 02:26:00'),
 147: Timestamp('2024-01-01 02:27:00'),
 148: Timestamp('2024-01-01 02:28:00'),
 149: Timestamp('2024-01-01 02:29:00'),
 150: Timestamp('2024-01-01 02:30:00'),
 151: Timestamp('2024-01-01 02:31:00'),
 152: Timestamp('2024-01-01 02:32:00'),
 153: Timestamp('2024-01-01 02:33:00'),
 154: Timestamp('2024-01-01 02:34:00'),
 155: Timestamp('2024-01-01 02:35:00'),
 156: Timestamp('2024-01-01 02:36:00'),
 157: Timestamp('2024-01-01 02:37:00'),
 158: Timestamp('2024-01-01 02:38:00'),
 159: Timestamp('2024-01-01 02:39:00'),
 160: Timestamp('2024-01-01 02:40:00'),
 161: Timestamp('2024-01-01 02:41:00'),
 162: Timestamp('2024-01-01 02:42:00'),
 163: Timestamp('2024-01-01 02:43:00'),
 164: Timestamp('2024-01-01 02:44:00'),
 165: Timestamp('2024-01-01 02:45:00'),
 166: Timestamp('2024-01-01 02:46:00'),
 167: Timestamp('2024-01-01 02:47:00'),
 168: Timestamp('2024-01-01 02:48:00'),
 169: Timestamp('2024-01-01 02:49:00'),
 170: Timestamp('2024-01-01 02:50:00'),
 171: Timestamp('2024-01-01 02:51:00'),
 172: Timestamp('2024-01-01 02:52:00'),
 173: Timestamp('2024-01-01 02:53:00'),
 174: Timestamp('2024-01-01 02:54:00'),
 175: Timestamp('2024-01-01 02:55:00'),
 176: Timestamp('2024-01-01 02:56:00'),
 177: Timestamp('2024-01-01 02:57:00'),
 178: Timestamp('2024-01-01 02:58:00'),
 179: Timestamp('2024-01-01 02:59:00'),
 180: Timestamp('2024-01-01 03:00:00'),
 181: Timestamp('2024-01-01 03:01:00'),
 182: Timestamp('2024-01-01 03:02:00'),
 183: Timestamp('2024-01-01 03:03:00'),
 184: Timestamp('2024-01-01 03:04:00'),
 185: Timestamp('2024-01-01 03:05:00'),
 186: Timestamp('2024-01-01 03:06:00'),
 187: Timestamp('2024-01-01 03:07:00'),
 188: Timestamp('2024-01-01 03:08:00'),
 189: Timestamp('2024-01-01 03:09:00'),
 190: Timestamp('2024-01-01 03:10:00'),
 191: Timestamp('2024-01-01 03:11:00'),
 192: Timestamp('2024-01-01 03:12:00'),
 193: Timestamp('2024-01-01 03:13:00'),
 194: Timestamp('2024-01-01 03:14:00'),
 195: Timestamp('2024-01-01 03:15:00'),
 196: Timestamp('2024-01-01 03:16:00'),
 197: Timestamp('2024-01-01 03:17:00'),
 198: Timestamp('2024-01-01 03:18:00'),
 199: Timestamp('2024-01-01 03:19:00'),
 200: Timestamp('2024-01-01 03:20:00'),
 201: Timestamp('2024-01-01 03:21:00'),
 202: Timestamp('2024-01-01 03:22:00'),
 203: Timestamp('2024-01-01 03:23:00'),
 204: Timestamp('2024-01-01 03:24:00'),
 205: Timestamp('2024-01-01 03:25:00'),
 206: Timestamp('2024-01-01 03:26:00'),
 207: Timestamp('2024-01-01 03:27:00'),
 208: Timestamp('2024-01-01 03:28:00'),
 209: Timestamp('2024-01-01 03:29:00'),
 210: Timestamp('2024-01-01 03:30:00'),
 211: Timestamp('2024-01-01 03:31:00'),
 212: Timestamp('2024-01-01 03:32:00'),
 213: Timestamp('2024-01-01 03:33:00'),
 214: Timestamp('2024-01-01 03:34:00'),
 215: Timestamp('2024-01-01 03:35:00'),
 216: Timestamp('2024-01-01 03:36:00'),
 217: Timestamp('2024-01-01 03:37:00'),
 218: Timestamp('2024-01-01 03:38:00'),
 219: Timestamp('2024-01-01 03:39:00'),
 220: Timestamp('2024-01-01 03:40:00'),
 221: Timestamp('2024-01-01 03:41:00'),
 222: Timestamp('2024-01-01 03:42:00'),
 223: Timestamp('2024-01-01 03:43:00'),
 224: Timestamp('2024-01-01 03:44:00'),
 225: Timestamp('2024-01-01 03:45:00'),
 226: Timestamp('2024-01-01 03:46:00'),
 227: Timestamp('2024-01-01 03:47:00'),
 228: Timestamp('2024-01-01 03:48:00'),
 229: Timestamp('2024-01-01 03:49:00'),
 230: Timestamp('2024-01-01 03:50:00'),
 231: Timestamp('2024-01-01 03:51:00'),
 232: Timestamp('2024-01-01 03:52:00'),
 233: Timestamp('2024-01-01 03:53:00'),
 234: Timestamp('2024-01-01 03:54:00'),
 235: Timestamp('2024-01-01 03:55:00'),
 236: Timestamp('2024-01-01 03:56:00'),
 237: Timestamp('2024-01-01 03:57:00'),
 238: Timestamp('2024-01-01 03:58:00'),
 239: Timestamp('2024-01-01 03:59:00'),
 240: Timestamp('2024-01-01 04:00:00'),
 241: Timestamp('2024-01-01 04:01:00'),
 242: Timestamp('2024-01-01 04:02:00'),
 243: Timestamp('2024-01-01 04:03:00'),
 244: Timestamp('2024-01-01 04:04:00'),
 245: Timestamp('2024-01-01 04:05:00'),
 246: Timestamp('2024-01-01 04:06:00'),
 247: Timestamp('2024-01-01 04:07:00'),
 248: Timestamp('2024-01-01 04:08:00'),
 249: Timestamp('2024-01-01 04:09:00'),
 250: Timestamp('2024-01-01 04:10:00'),
 251: Timestamp('2024-01-01 04:11:00'),
 252: Timestamp('2024-01-01 04:12:00'),
 253: Timestamp('2024-01-01 04:13:00'),
 254: Timestamp('2024-01-01 04:14:00'),
 255: Timestamp('2024-01-01 04:15:00'),
 256: Timestamp('2024-01-01 04:16:00'),
 257: Timestamp('2024-01-01 04:17:00'),
 258: Timestamp('2024-01-01 04:18:00'),
 259: Timestamp('2024-01-01 04:19:00'),
 260: Timestamp('2024-01-01 04:20:00'),
 261: Timestamp('2024-01-01 04:21:00'),
 262: Timestamp('2024-01-01 04:22:00'),
 263: Timestamp('2024-01-01 04:23:00'),
 264: Timestamp('2024-01-01 04:24:00'),
 265: Timestamp('2024-01-01 04:25:00'),
 266: Timestamp('2024-01-01 04:26:00'),
 267: Timestamp('2024-01-01 04:27:00'),
 268: Timestamp('2024-01-01 04:28:00'),
 269: Timestamp('2024-01-01 04:29:00'),
 270: Timestamp('2024-01-01 04:30:00'),
 271: Timestamp('2024-01-01 04:31:00'),
 272: Timestamp('2024-01-01 04:32:00'),
 273: Timestamp('2024-01-01 04:33:00'),
 274: Timestamp('2024-01-01 04:34:00'),
 275: Timestamp('2024-01-01 04:35:00'),
 276: Timestamp('2024-01-01 04:36:00'),
 277: Timestamp('2024-01-01 04:37:00'),
 278: Timestamp('2024-01-01 04:38:00'),
 279: Timestamp('2024-01-01 04:39:00'),
 280: Timestamp('2024-01-01 04:40:00'),
 281: Timestamp('2024-01-01 04:41:00'),
 282: Timestamp('2024-01-01 04:42:00'),
 283: Timestamp('2024-01-01 04:43:00'),
 284: Timestamp('2024-01-01 04:44:00'),
 285: Timestamp('2024-01-01 04:45:00'),
 286: Timestamp('2024-01-01 04:46:00'),
 287: Timestamp('2024-01-01 04:47:00'),
 288: Timestamp('2024-01-01 04:48:00'),
 289: Timestamp('2024-01-01 04:49:00'),
 290: Timestamp('2024-01-01 04:50:00'),
 291: Timestamp('2024-01-01 04:51:00'),
 292: Timestamp('2024-01-01 04:52:00'),
 293: Timestamp('2024-01-01 04:53:00'),
 294: Timestamp('2024-01-01 04:54:00'),
 295: Timestamp('2024-01-01 04:55:00'),
 296: Timestamp('2024-01-01 04:56:00'),
 297: Timestamp('2024-01-01 04:57:00'),
 298: Timestamp('2024-01-01 04:58:00'),
 299: Timestamp('2024-01-01 04:59:00'),
 300: Timestamp('2024-01-01 05:00:00'),
 301: Timestamp('2024-01-01 05:01:00'),
 302: Timestamp('2024-01-01 05:02:00'),
 303: Timestamp('2024-01-01 05:03:00'),
 304: Timestamp('2024-01-01 05:04:00'),
 305: Timestamp('2024-01-01 05:05:00'),
 306: Timestamp('2024-01-01 05:06:00'),
 307: Timestamp('2024-01-01 05:07:00'),
 308: Timestamp('2024-01-01 05:08:00'),
 309: Timestamp('2024-01-01 05:09:00'),
 310: Timestamp('2024-01-01 05:10:00'),
 311: Timestamp('2024-01-01 05:11:00'),
 312: Timestamp('2024-01-01 05:12:00'),
 313: Timestamp('2024-01-01 05:13:00'),
 314: Timestamp('2024-01-01 05:14:00'),
 315: Timestamp('2024-01-01 05:15:00'),
 316: Timestamp('2024-01-01 05:16:00'),
 317: Timestamp('2024-01-01 05:17:00'),
 318: Timestamp('2024-01-01 05:18:00'),
 319: Timestamp('2024-01-01 05:19:00'),
 320: Timestamp('2024-01-01 05:20:00'),
 321: Timestamp('2024-01-01 05:21:00'),
 322: Timestamp('2024-01-01 05:22:00'),
 323: Timestamp('2024-01-01 05:23:00'),
 324: Timestamp('2024-01-01 05:24:00'),
 325: Timestamp('2024-01-01 05:25:00'),
 326: Timestamp('2024-01-01 05:26:00'),
 327: Timestamp('2024-01-01 05:27:00'),
 328: Timestamp('2024-01-01 05:28:00'),
 329: Timestamp('2024-01-01 05:29:00'),
 330: Timestamp('2024-01-01 05:30:00'),
 331: Timestamp('2024-01-01 05:31:00'),
 332: Timestamp('2024-01-01 05:32:00'),
 333: Timestamp('2024-01-01 05:33:00'),
 334: Timestamp('2024-01-01 05:34:00'),
 335: Timestamp('2024-01-01 05:35:00'),
 336: Timestamp('2024-01-01 05:36:00'),
 337: Timestamp('2024-01-01 05:37:00'),
 338: Timestamp('2024-01-01 05:38:00'),
 339: Timestamp('2024-01-01 05:39:00'),
 340: Timestamp('2024-01-01 05:40:00'),
 341: Timestamp('2024-01-01 05:41:00'),
 342: Timestamp('2024-01-01 05:42:00'),
 343: Timestamp('2024-01-01 05:43:00'),
 344: Timestamp('2024-01-01 05:44:00'),
 345: Timestamp('2024-01-01 05:45:00'),
 346: Timestamp('2024-01-01 05:46:00'),
 347: Timestamp('2024-01-01 05:47:00'),
 348: Timestamp('2024-01-01 05:48:00'),
 349: Timestamp('2024-01-01 05:49:00'),
 350: Timestamp('2024-01-01 05:50:00'),
 351: Timestamp('2024-01-01 05:51:00'),
 352: Timestamp('2024-01-01 05:52:00'),
 353: Timestamp('2024-01-01 05:53:00'),
 354: Timestamp('2024-01-01 05:54:00'),
 355: Timestamp('2024-01-01 05:55:00'),
 356: Timestamp('2024-01-01 05:56:00'),
 357: Timestamp('2024-01-01 05:57:00'),
 358: Timestamp('2024-01-01 05:58:00'),
 359: Timestamp('2024-01-01 05:59:00'),
 360: Timestamp('2024-01-01 06:00:00'),
 361: Timestamp('2024-01-01 06:01:00'),
 362: Timestamp('2024-01-01 06:02:00'),
 363: Timestamp('2024-01-01 06:03:00'),
 364: Timestamp('2024-01-01 06:04:00'),
 365: Timestamp('2024-01-01 06:05:00'),
 366: Timestamp('2024-01-01 06:06:00'),
 367: Timestamp('2024-01-01 06:07:00'),
 368: Timestamp('2024-01-01 06:08:00'),
 369: Timestamp('2024-01-01 06:09:00'),
 370: Timestamp('2024-01-01 06:10:00'),
 371: Timestamp('2024-01-01 06:11:00'),
 372: Timestamp('2024-01-01 06:12:00'),
 373: Timestamp('2024-01-01 06:13:00'),
 374: Timestamp('2024-01-01 06:14:00'),
 375: Timestamp('2024-01-01 06:15:00'),
 376: Timestamp('2024-01-01 06:16:00'),
 377: Timestamp('2024-01-01 06:17:00'),
 378: Timestamp('2024-01-01 06:18:00'),
 379: Timestamp('2024-01-01 06:19:00'),
 380: Timestamp('2024-01-01 06:20:00'),
 381: Timestamp('2024-01-01 06:21:00'),
 382: Timestamp('2024-01-01 06:22:00'),
 383: Timestamp('2024-01-01 06:23:00'),
 384: Timestamp('2024-01-01 06:24:00'),
 385: Timestamp('2024-01-01 06:25:00'),
 386: Timestamp('2024-01-01 06:26:00'),
 387: Timestamp('2024-01-01 06:27:00'),
 388: Timestamp('2024-01-01 06:28:00'),
 389: Timestamp('2024-01-01 06:29:00'),
 390: Timestamp('2024-01-01 06:30:00'),
 391: Timestamp('2024-01-01 06:31:00'),
 392: Timestamp('2024-01-01 06:32:00'),
 393: Timestamp('2024-01-01 06:33:00'),
 394: Timestamp('2024-01-01 06:34:00'),
 395: Timestamp('2024-01-01 06:35:00'),
 396: Timestamp('2024-01-01 06:36:00'),
 397: Timestamp('2024-01-01 06:37:00'),
 398: Timestamp('2024-01-01 06:38:00'),
 399: Timestamp('2024-01-01 06:39:00'),
 400: Timestamp('2024-01-01 06:40:00'),
 401: Timestamp('2024-01-01 06:41:00'),
 402: Timestamp('2024-01-01 06:42:00'),
 403: Timestamp('2024-01-01 06:43:00'),
 404: Timestamp('2024-01-01 06:44:00'),
 405: Timestamp('2024-01-01 06:45:00'),
 406: Timestamp('2024-01-01 06:46:00'),
 407: Timestamp('2024-01-01 06:47:00'),
 408: Timestamp('2024-01-01 06:48:00'),
 409: Timestamp('2024-01-01 06:49:00'),
 410: Timestamp('2024-01-01 06:50:00'),
 411: Timestamp('2024-01-01 06:51:00'),
 412: Timestamp('2024-01-01 06:52:00'),
 413: Timestamp('2024-01-01 06:53:00'),
 414: Timestamp('2024-01-01 06:54:00'),
 415: Timestamp('2024-01-01 06:55:00'),
 416: Timestamp('2024-01-01 06:56:00'),
 417: Timestamp('2024-01-01 06:57:00'),
 418: Timestamp('2024-01-01 06:58:00'),
 419: Timestamp('2024-01-01 06:59:00'),
 420: Timestamp('2024-01-01 07:00:00'),
 421: Timestamp('2024-01-01 07:01:00'),
 422: Timestamp('2024-01-01 07:02:00'),
 423: Timestamp('2024-01-01 07:03:00'),
 424: Timestamp('2024-01-01 07:04:00'),
 425: Timestamp('2024-01-01 07:05:00'),
 426: Timestamp('2024-01-01 07:06:00'),
 427: Timestamp('2024-01-01 07:07:00'),
 428: Timestamp('2024-01-01 07:08:00'),
 429: Timestamp('2024-01-01 07:09:00'),
 430: Timestamp('2024-01-01 07:10:00'),
 431: Timestamp('2024-01-01 07:11:00'),
 432: Timestamp('2024-01-01 07:12:00'),
 433: Timestamp('2024-01-01 07:13:00'),
 434: Timestamp('2024-01-01 07:14:00'),
 435: Timestamp('2024-01-01 07:15:00'),
 436: Timestamp('2024-01-01 07:16:00'),
 437: Timestamp('2024-01-01 07:17:00'),
 438: Timestamp('2024-01-01 07:18:00'),
 439: Timestamp('2024-01-01 07:19:00'),
 440: Timestamp('2024-01-01 07:20:00'),
 441: Timestamp('2024-01-01 07:21:00'),
 442: Timestamp('2024-01-01 07:22:00'),
 443: Timestamp('2024-01-01 07:23:00'),
 444: Timestamp('2024-01-01 07:24:00'),
 445: Timestamp('2024-01-01 07:25:00'),
 446: Timestamp('2024-01-01 07:26:00'),
 447: Timestamp('2024-01-01 07:27:00'),
 448: Timestamp('2024-01-01 07:28:00'),
 449: Timestamp('2024-01-01 07:29:00'),
 450: Timestamp('2024-01-01 07:30:00'),
 451: Timestamp('2024-01-01 07:31:00'),
 452: Timestamp('2024-01-01 07:32:00'),
 453: Timestamp('2024-01-01 07:33:00'),
 454: Timestamp('2024-01-01 07:34:00'),
 455: Timestamp('2024-01-01 07:35:00'),
 456: Timestamp('2024-01-01 07:36:00'),
 457: Timestamp('2024-01-01 07:37:00'),
 458: Timestamp('2024-01-01 07:38:00'),
 459: Timestamp('2024-01-01 07:39:00'),
 460: Timestamp('2024-01-01 07:40:00'),
 461: Timestamp('2024-01-01 07:41:00'),
 462: Timestamp('2024-01-01 07:42:00'),
 463: Timestamp('2024-01-01 07:43:00'),
 464: Timestamp('2024-01-01 07:44:00'),
 465: Timestamp('2024-01-01 07:45:00'),
 466: Timestamp('2024-01-01 07:46:00'),
 467: Timestamp('2024-01-01 07:47:00'),
 468: Timestamp('2024-01-01 07:48:00'),
 469: Timestamp('2024-01-01 07:49:00'),
 470: Timestamp('2024-01-01 07:50:00'),
 471: Timestamp('2024-01-01 07:51:00'),
 472: Timestamp('2024-01-01 07:52:00'),
 473: Timestamp('2024-01-01 07:53:00'),
 474: Timestamp('2024-01-01 07:54:00'),
 475: Timestamp('2024-01-01 07:55:00'),
 476: Timestamp('2024-01-01 07:56:00'),
 477: Timestamp('2024-01-01 07:57:00'),
 478: Timestamp('2024-01-01 07:58:00'),
 479: Timestamp('2024-01-01 07:59:00'),
 480: Timestamp('2024-01-01 08:00:00'),
 481: Timestamp('2024-01-01 08:01:00'),
 482: Timestamp('2024-01-01 08:02:00'),
 483: Timestamp('2024-01-01 08:03:00'),
 484: Timestamp('2024-01-01 08:04:00'),
 485: Timestamp('2024-01-01 08:05:00'),
 486: Timestamp('2024-01-01 08:06:00'),
 487: Timestamp('2024-01-01 08:07:00'),
 488: Timestamp('2024-01-01 08:08:00'),
 489: Timestamp('2024-01-01 08:09:00'),
 490: Timestamp('2024-01-01 08:10:00'),
 491: Timestamp('2024-01-01 08:11:00'),
 492: Timestamp('2024-01-01 08:12:00'),
 493: Timestamp('2024-01-01 08:13:00'),
 494: Timestamp('2024-01-01 08:14:00'),
 495: Timestamp('2024-01-01 08:15:00'),
 496: Timestamp('2024-01-01 08:16:00'),
 497: Timestamp('2024-01-01 08:17:00'),
 498: Timestamp('2024-01-01 08:18:00'),
 499: Timestamp('2024-01-01 08:19:00'),
 500: Timestamp('2024-01-01 08:20:00'),
 501: Timestamp('2024-01-01 08:21:00'),

In [5]:
pd.DataFrame(df['customer_id'])

     customer_id
0          ADX_0
1          ADX_1
2          ADX_2
3          ADX_3
4          ADX_4
...          ...
9995    ADX_9995
9996    ADX_9996
9997    ADX_9997
9998    ADX_9998
9999    ADX_9999

[10000 rows x 1 columns]

In [6]:
pd.read_parquet("eda_banking.parquet")

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned,Fraud,RiskScore,BalancePerProduct,AgeRisk,HighValueCustomer,LowCreditRisk,MarketingScore,ComplainFlag,LowSatisfaction,OperationalRiskScore,event_timestamp,customer_id
0,619,France,Female,42,2,11983969.0,1,1,1,10134888.0,1,1,2,DIAMOND,464,0,1,0.000000,0,0,0,0,1,1,2,2024-01-01 00:00:00,ADX_0
1,608,Spain,Female,41,1,8380786.0,1,0,1,11254258.0,0,1,3,DIAMOND,456,0,1,41903.930000,0,0,0,1,1,0,1,2024-01-01 00:01:00,ADX_1
2,502,France,Female,42,8,15966080.0,3,1,0,11393157.0,1,1,3,DIAMOND,377,0,3,39915.200000,0,1,0,1,1,0,2,2024-01-01 00:02:00,ADX_2
3,699,France,Female,39,1,11983969.0,2,0,0,9382663.0,0,0,5,GOLD,350,0,1,0.000000,0,0,0,0,0,0,1,2024-01-01 00:03:00,ADX_3
4,850,Spain,Female,43,2,12551082.0,1,1,1,7908410.0,0,0,5,GOLD,425,0,1,62755.410000,0,1,0,2,0,0,0,2024-01-01 00:04:00,ADX_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,11983969.0,2,1,0,9627064.0,0,0,1,DIAMOND,300,0,1,0.000000,0,0,0,0,0,1,2,2024-01-07 22:35:00,ADX_9995
9996,516,France,Male,35,10,5736961.0,1,1,1,10169977.0,0,0,5,PLATINUM,771,0,0,28684.805000,0,0,0,0,0,0,0,2024-01-07 22:36:00,ADX_9996
9997,709,France,Female,36,7,11983969.0,1,0,1,4208558.0,1,1,3,SILVER,564,0,1,0.000000,0,0,0,0,1,0,1,2024-01-07 22:37:00,ADX_9997
9998,772,Germany,Male,42,3,7507531.0,2,1,0,9288852.0,1,1,2,GOLD,339,1,2,25025.103333,0,0,0,1,1,1,3,2024-01-07 22:38:00,ADX_9998
9999,792,France,Female,28,4,13014279.0,1,1,0,3819078.0,0,0,3,DIAMOND,911,0,2,65071.395000,0,1,0,1,0,0,1,2024-01-07 22:39:00,ADX_9999

In [7]:
df[df['customer_id', 'Fraud']]

KeyError: ('customer_id', 'Fraud')

In [ ]:
df['HighValueCustomer'].value_counts()

HighValueCustomer
0    5201
1    4799
Name: count, dtype: int64

In [ ]:
df['ComplainFlag'].value_counts()

ComplainFlag
0    7956
1    2044
Name: count, dtype: int64